### PR TITLE
OneRFID - Reset Dessicant Button + Control Dessicant Frequency

### LINKED ISSUE #24: [Feature Request]: Reset Dessicant Reminder
### Device model name

I think all feeder models?

### Device model number

I think all feeder models?

### Device type

Feeder

### Feature name

Reset Dessicant Reminder

### Describe the feature

Ability to reset (and potentially set the timeout as well?) for the dessicant reminder:

API endpoint:
https://api.us.petlibro.com/device/device/desiccantReset

post request data:
```
{
  "deviceSn": "AF06013AF056214A2",
  "requestId": "2089bebb53034ef0ae04ee1bb3b3aa55",
  "timeout": 5000
}
```

response data:
```
{
  "code": 0,
  "msg": null,
  "data": null
}
```

the frequency seems to be set seperately in this endpoint:
https://api.us.petlibro.com/device/device/maintenanceFrequencySetting

post request data:
```
{
  "deviceSn": "AF06013AF056214A2",
  "key": "DESICCANT",
  "frequency": 60,
  "requestId": "6ede2055ec5344beba5fbb3755b63c5a",
  "timeout": 5000
}
```

response data:
```
{
  "code": 0,
  "msg": null,
  "data": null
}
```
### What problem does this feature solve?

More control from homeassistant rather than app.

### Available to help with the feature development

- [X] I agree to help with testing or providing relevant information for this feature request

### PR DESCRIPTION
**Pull request by C4-Dimitri**
Could be applied to other devices as well. i just havent yet, as i dont want to touch too much that i dont understand and cant test.
resolves: #24

### CODE REVIEW

**Comment by jjjonesjr33** [comment]
@C4-Dimitri  This one its stating that there are some conflicting files before I can merge.

`custom_components/petlibro/devices/feeders/one_rfid_smart_feeder.py`
`custom_components/petlibro/number.py`

**Review by jjjonesjr33 — CHANGES_REQUESTED** [review]
@C4-Dimitri  This one its stating that there are some conflicting files before I can merge.

`custom_components/petlibro/devices/feeders/one_rfid_smart_feeder.py`
`custom_components/petlibro/number.py`

**Review by C4-Dimitri — COMMENTED** [review]
Conflicts should now be resolved. conflicts were only there because how i had done my branches.

**Comment by C4-Dimitri** [comment]
having some issues getting the "DESSICANT" keyword that is required in the frequency update request to be dynamic. dont merge until i have this fixed. ill try and resolve this as soon as i can. if you have some insight on this that would be great - i am really struggling, as it seems like no matter what i do i am getting to an Exception in the async def async_set_native_value

where i get 
Error setting value 40.0 for Marble's Feeder: OneRFIDSmartFeeder.set_desiccant_frequency() got an unexpected keyword argument 'replacetype'

in the logs when trying to set the value to something new. i know i shouldnt pass replacetype to async def async_set_native_value, but i dont know how to split it out, because i do need to pass it to async def set_desiccant_frequency as its needed.

**Comment by C4-Dimitri** [comment]
Ive given up on making it dynamic from the DEVICE_NUMBER_MAP, as i realised that only a few devices will have a different key + its probably actually good to maintain different names for the block that actually handles the request - just in case they have more fields i havent considered.

**Comment by C4-Dimitri** [comment]
now ready for merge.

**Review by jjjonesjr33 — APPROVED** [review]

**Comment by jjjonesjr33** [comment]
Great work @C4-Dimitri

**Pull request merged**
