### PR TITLE
Implement Granary Smart Feeder

### PR DESCRIPTION
**Pull request by jherby2k**
This enables everything on the Granary Smart Feeder too, except for Eating Times. Tests OK here. Could use some refactoring now as the two devices are nearly identical.

### CODE REVIEW

**Comment by jherby2k** [comment]
image

**Comment by jjjonesjr33** [comment]
Looks great! the only thing I think we would need to remove then from the code is in granary_smart_feeder.py is for the Eating Times here:
```pyton
    @property
    def today_eating_times(self) -> int:
        return self._data.get("grainStatus", {}).get("todayEatingTimes", 0)
 ```
 and
 ```python
         PetLibroSensorEntityDescription[GranarySmartFeeder](
            key="today_eating_times",
            translation_key="today_eating_times",
            icon="mdi:history",
            state_class=SensorStateClass.TOTAL_INCREASING,
            name="Today Eating Times"
        ),
```
And then in the `binary_sensor.py` to remove the Lid as that's not a feature of this device.
```python
        PetLibroBinarySensorEntityDescription[GranarySmartFeeder](
            key="door_state",
            translation_key="door_state",
            icon="mdi:door",
            device_class=BinarySensorDeviceClass.DOOR,
            should_report=lambda device: device.door_state is not None,
            name="Lid"
        ),
```
and 
```python
        PetLibroBinarySensorEntityDescription[GranarySmartFeeder](
            key="door_blocked",
            translation_key="door_blocked",
            icon="mdi:door",
            device_class=BinarySensorDeviceClass.PROBLEM,
            should_report=lambda device: device.door_blocked is not None,
            name="Lid Status"
        ),
```
The only last thing I would want to confirm is the `cups` being dispensed and to make sure it is showing the correct amount. I know in the RFID one I had to correct that.

**Comment by jherby2k** [comment]
I did remove the Eating stuff already, but you're right about the Lid. Removed also.

I can confirm the `cups` is correct - matches what's in the app.

**Comment by jjjonesjr33** [comment]
Thanks! Adding it in now. Will push a release in a moment.

**Pull request merged**
