### PR TITLE
Add Support for Manual Lid Opening & On/Off of Display Matrix for OneRFIDFeeder PLAF301

### PR DESCRIPTION
**Pull request by C4-Dimitri**
Sorry for the notification spam - just trying to clean up the mess i made when testing.

Resolves Issue #15
Resolves Issue #20
Resolves Issue #27

Tested and working on my devices.

We can keep this open to develop the timeout feature for the lid closing automatically. or i can open a new Feature Request for it.
We can keep this open to develop the different built in icons, and the text options. or i can open a new Feature Request for just those features, and i can then slowly develop this instead.

### CODE REVIEW

**Comment by jjjonesjr33** [comment]
I'm not at the house today or I would test. Just reviewing in this you have the lid opening and it looks like you have a way to turn the display on and off?

I wonder if the sound can be controlled via the same method?

**Comment by C4-Dimitri** [comment]
> I'm not at the house today or I would test. Just reviewing in this you have the lid opening and it looks like you have a way to turn the display on and off?
> 
> I wonder if the sound can be controlled via the same method?

Correct. both working - so lid will manually open with button press. and then i have an on button, and an off button for the display. not a toggle.

here is what the sound api data looks like:
post request endpoint:
https://api.us.petlibro.com/device/setting/updateSoundSetting

post request data (`off `command):
```
{
  "deviceSn": "AF06013AF056214A2",
  "soundSwitch": false,
  "soundAgingType": 1,
  "soundStartTime": null,
  "soundEndTime": null
}
```
post request data (`on`command):
```
{
  "deviceSn": "AF06013AF056214A2",
  "soundSwitch": true,
  "soundAgingType": 1,
  "soundStartTime": null,
  "soundEndTime": null
}
```

same response for both:

```
{
  "code": 0,
  "msg": null,
  "data": null
}
```

so yes, you could 100% do the same for the sound.

**Review by jjjonesjr33 — CHANGES_REQUESTED** [review]
Comment on https://github.com/jjjonesjr33/petlibro/issues/20 - The only thought I had was to shorted the naming on the buttons and in the translations.

**Comment by jjjonesjr33** [comment]
> here is what the sound api data looks like: post request endpoint: https://api.us.petlibro.com/device/setting/updateSoundSetting

On the sound I think we need a Feature Request put in for it.

**Review by C4-Dimitri — COMMENTED** [review]
Names now shortened. + sound on/off now working as well.

**Review by jjjonesjr33 — APPROVED** [review]
This looks awesome! Great work @C4-Dimitri

**Comment by jjjonesjr33** [comment]
@C4-Dimitri on issue https://github.com/jjjonesjr33/petlibro/issues/27, do you want me to leave this open still for adding the ability to "set volume to specific amount 1 - 100"? Let me know what you think.

Also the only thing that I think we might be missing is a sensor to show if the sound is currently off/on. I should be able to figure that one out this week for us.

**Comment by C4-Dimitri** [comment]
I would say "ship it" for now, and i can work on that bit later.

**Pull request merged**
